name: Flutter CI/CD - Build APK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2️⃣ Устанавливаем Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3️⃣ Создаём android/ios структуры (если их нет)
      - name: Create Flutter project structure
        run: flutter create .

      # 4️⃣ Получаем зависимости
      - name: Install dependencies
        run: flutter pub get

      # 5️⃣ Сборка APK
      - name: Build APK (release)
        run: flutter build apk --release

      # 6️⃣ Загрузка APK как артефакта
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
